### ISSUE TITLE
an end to end pipeline (from data ingestion through training to evaluation) is now available!

### ISSUE THREAD

**Issue by radekosmulski** [earthspecies/audio-embeddings#3]
I just wanted to give a quick update that I just pushed [a new notebook](https://github.com/earthspecies/unsupervised-audio-translation/blob/main/02_basic_model_with_teacher_forcing.ipynb) to the repository. In this notebook we

* load the data we processed in [the first notebook](https://github.com/earthspecies/unsupervised-audio-translation/blob/main/01_a_first_look_at_librispeech.ipynb)
* define an auto encoder architecture
* train the model
* evaluate results and compare with the [embeddings](https://github.com/earthspecies/unsupervised-audio-translation/blob/main/01_a_first_look_at_librispeech.ipynb) shared by the authors of [the paper](https://arxiv.org/abs/1803.08976) we are working on implementing

The model trains but unfortunately, in the minimal testing that I've done, it doesn't seem to be learning a well structured embedding space. There are many tweaks that could be done to the model, it is also not unlikely that we have a bug somewhere.

I am in the process of creating and testing out a mini dataset to experiment not. In the meanwhile I am also planning to spend a bit more time going over the architecture and data processing and will reach out to one of the authors of the paper asking for guidance. Will report back here as I make progress on this.

**Comment by bs** [comment]
@radekosmulski, is there anything more we need from this cycle of work before closing this?

**Comment by radekosmulski** [comment]
don't believe so - closing
